### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by gibatronic** [lagden/io-cep-cli#1]
![image](https://cloud.githubusercontent.com/assets/819643/22020800/44e28d08-dca1-11e6-8738-157f3e808631.png)

**Comment by lagden** [comment]
O problema está na lib... https://github.com/lagden/io-cep
Estou revisando... 👍

**Comment by lagden** [comment]
@gibatronic tks!!

<img width="450" alt="screen shot 2017-01-18 at 13 01 15" src="https://cloud.githubusercontent.com/assets/130963/22069023/221f4b8e-dd7e-11e6-929b-8dd8c5cacb5d.png">

**Comment by gibatronic** [comment]
excelente, valeu!
